; ════════════════════════════════════════════════════════════════════════════════
;  RSU — VANET Roadside Unit
;  Board  : ESP32 Dev Board
;  IDE    : VS Code + PlatformIO
; ════════════════════════════════════════════════════════════════════════════════

[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
upload_speed  = 115200        ; ← add this line (default 921600 is too fast)
lib_ldf_mode  = deep+
build_flags   = -I include

lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  sandeepmistry/LoRa    @ ^0.8.0

  
; SD, SPI, WiFi, HTTPClient, HardwareSerial, Preferences
; are all built into the ESP32 Arduino framework — no install needed
